spring:
    datasource:
        driverClassName: org.postgresql.Driver
        password: postgres
        url: jdbc:postgresql://localhost:5432/superkasska
        username: postgres
    jpa:
        show-sql: true

    sql:
        init:
            mode: always
